# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abb2997fbceca07c29aac92ea83dc7bca5d97b678ad1d1dc46adb5fac2d9ee11a65fc805f30c4308e4e2012038777110c3a26d1f1b2b0111223760844a19ac8b
  yelp_consumer_key: <%= Figaro.env.YELP_CONSUMER_KEY %>
  yelp_consumer_secret: <%= Figaro.env.YELP_CONSUMER_SECRET %>
  yelp_token: <%= Figaro.env.YELP_TOKEN %>
  yelp_token_secret: <%= Figaro.env.YELP_TOKEN_SECRET %>

test:
  secret_key_base: bc5b04ff011ad4ad4f7451f4d982c9a422fef93f688653c40f756c98ddbac26208618189d4dcec1648f58cebbdac155eea0f643877dd2f29fcea837cfc82f52d
  yelp_consumer_key: <%= Figaro.env.YELP_CONSUMER_KEY %>
  yelp_consumer_secret: <%= Figaro.env.YELP_CONSUMER_SECRET %>
  yelp_token: <%= Figaro.env.YELP_TOKEN %>
  yelp_token_secret: <%= Figaro.env.YELP_TOKEN_SECRET %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yelp_consumer_key: <%= ENV["YELP_CONSUMER_KEY"] %>
  yelp_consumer_secret: <%= ENV["YELP_CONSUMER_SECRET"] %>
  yelp_token: <%= ENV["YELP_TOKEN"] %>
  yelp_token_secret: <%= ENV["YELP_TOKEN_SECRET"] %>
